# app/config/instrument_map.py

# SL buffer: 2 pips (0.00020 for 5-decimal, 0.020 for 3-decimal)
# TP ratio: 6R

INSTRUMENT_MAP = {
    # ── OANDA forex ──
    "OANDA:USDCHF": {
        "broker": "oanda",
        "oanda": "USD_CHF",
        "decimals": 5,
        "step": 1,
        "base_currency": "CHF",
        "tp_ratio": 6.0,
        "sl_buffer": 0.00020,
    },
    "OANDA:EURUSD": {
        "broker": "oanda",
        "oanda": "EUR_USD",
        "decimals": 5,
        "step": 1,
        "base_currency": "USD",
        "tp_ratio": 6.0,
        "sl_buffer": 0.00020,
    },
    "OANDA:USDJPY": {
        "broker": "oanda",
        "oanda": "USD_JPY",
        "decimals": 3,
        "step": 1,
        "base_currency": "JPY",
        "tp_ratio": 6.0,
        "sl_buffer": 0.020,
    },
    "OANDA:GBPUSD": {
        "broker": "oanda",
        "oanda": "GBP_USD",
        "decimals": 5,
        "step": 1,
        "base_currency": "USD",
        "tp_ratio": 6.0,
        "sl_buffer": 0.00020,
    },
    "OANDA:EURGBP": {
        "broker": "oanda",
        "oanda": "EUR_GBP",
        "decimals": 5,
        "step": 1,
        "base_currency": "GBP",
        "tp_ratio": 6.0,
        "sl_buffer": 0.00020,
    },
    "OANDA:EURJPY": {
        "broker": "oanda",
        "oanda": "EUR_JPY",
        "decimals": 3,
        "step": 1,
        "base_currency": "JPY",
        "tp_ratio": 6.0,
        "sl_buffer": 0.020,
    },
    "OANDA:GBPJPY": {
        "broker": "oanda",
        "oanda": "GBP_JPY",
        "decimals": 3,
        "step": 1,
        "base_currency": "JPY",
        "tp_ratio": 6.0,
        "sl_buffer": 0.020,
    },
    "OANDA:AUDUSD": {
        "broker": "oanda",
        "oanda": "AUD_USD",
        "decimals": 5,
        "step": 1,
        "base_currency": "USD",
        "tp_ratio": 6.0,
        "sl_buffer": 0.00020,
    },
    "OANDA:NZDUSD": {
        "broker": "oanda",
        "oanda": "NZD_USD",
        "decimals": 5,
        "step": 1,
        "base_currency": "USD",
        "tp_ratio": 6.0,
        "sl_buffer": 0.00020,
    },
    "OANDA:USDCAD": {
        "broker": "oanda",
        "oanda": "USD_CAD",
        "decimals": 5,
        "step": 1,
        "base_currency": "CAD",
        "tp_ratio": 6.0,
        "sl_buffer": 0.00020,
    },
    # ── OANDA indices (CFDs) ──
    "OANDA:NAS100USD": {
        "broker": "oanda",
        "oanda": "NAS100_USD",
        "decimals": 1,
        "step": 0.1,
        "base_currency": "USD",
        "tp_ratio": 3.0,
        "sl_buffer": 10,
    },
    "OANDA:SPX500USD": {
        "broker": "oanda",
        "oanda": "SPX500_USD",
        "decimals": 1,
        "step": 0.1,
        "base_currency": "USD",
        "tp_ratio": 3.0,
        "sl_buffer": 5,
    },
    "OANDA:US30USD": {
        "broker": "oanda",
        "oanda": "US30_USD",
        "decimals": 1,
        "step": 0.1,
        "base_currency": "USD",
        "tp_ratio": 3.0,
        "sl_buffer": 15,
    },
    "OANDA:DE30EUR": {
        "broker": "oanda",
        "oanda": "DE30_EUR",
        "decimals": 1,
        "step": 0.1,
        "base_currency": "EUR",
        "tp_ratio": 3.0,
        "sl_buffer": 10,
    },
    "OANDA:UK100GBP": {
        "broker": "oanda",
        "oanda": "UK100_GBP",
        "decimals": 1,
        "step": 0.1,
        "base_currency": "GBP",
        "tp_ratio": 3.0,
        "sl_buffer": 5,
    },
    "OANDA:FR40EUR": {
        "broker": "oanda",
        "oanda": "FR40_EUR",
        "decimals": 1,
        "step": 0.1,
        "base_currency": "EUR",
        "tp_ratio": 3.0,
        "sl_buffer": 5,
    },
    # ── Kraken crypto ──
    "KRAKEN:BTCUSD": {
        "broker": "kraken",
        "pair": "XBTUSD",
        "decimals": 1,
        "step": 0.0001,
        "base_currency": "USD",
        "tp_ratio": 6.0,
        "sl_buffer": 100,
    },
    "KRAKEN:ETHUSD": {
        "broker": "kraken",
        "pair": "ETHUSD",
        "decimals": 2,
        "step": 0.01,
        "base_currency": "USD",
        "tp_ratio": 6.0,
        "sl_buffer": 5,
    },
    "KRAKEN:SOLUSD": {
        "broker": "kraken",
        "pair": "SOLUSD",
        "decimals": 2,
        "step": 0.1,
        "base_currency": "USD",
        "tp_ratio": 6.0,
        "sl_buffer": 0.5,
    },
    "KRAKEN:ADAUSD": {
        "broker": "kraken",
        "pair": "ADAUSD",
        "decimals": 6,
        "step": 1,
        "base_currency": "USD",
        "tp_ratio": 6.0,
        "sl_buffer": 0.005,
    },
    "KRAKEN:DOGEUSD": {
        "broker": "kraken",
        "pair": "XDGUSD",
        "decimals": 5,
        "step": 1,
        "base_currency": "USD",
        "tp_ratio": 6.0,
        "sl_buffer": 0.002,
    },
    "KRAKEN:XRPUSD": {
        "broker": "kraken",
        "pair": "XXRPZUSD",
        "decimals": 5,
        "step": 1,
        "base_currency": "USD",
        "tp_ratio": 6.0,
        "sl_buffer": 0.01,
    },
    "KRAKEN:LINKUSD": {
        "broker": "kraken",
        "pair": "LINKUSD",
        "decimals": 3,
        "step": 0.1,
        "base_currency": "USD",
        "tp_ratio": 6.0,
        "sl_buffer": 0.1,
    },
    "KRAKEN:XMRUSD": {
        "broker": "kraken",
        "pair": "XXMRZUSD",
        "decimals": 2,
        "step": 0.01,
        "base_currency": "USD",
        "tp_ratio": 6.0,
        "sl_buffer": 2,
    },
    "KRAKEN:PEPEUSD": {
        "broker": "kraken",
        "pair": "PEPEUSD",
        "decimals": 9,
        "step": 10000,
        "base_currency": "USD",
        "tp_ratio": 6.0,
        "sl_buffer": 0.0000005,
    },
    "KRAKEN:ATOMUSD": {
        "broker": "kraken",
        "pair": "ATOMUSD",
        "decimals": 4,
        "step": 0.1,
        "base_currency": "USD",
        "tp_ratio": 6.0,
        "sl_buffer": 0.05,
    },
}


def resolve_instrument(tv_symbol: str) -> dict | None:
    return INSTRUMENT_MAP.get(tv_symbol)
